var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                           xx     xxx           ",
   "                                                    xxx          xx!xx          ",
   "                                    o o      xx      |           x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                 o                                                           xx ",
   " xx            o                         o o                                 x  ",
   "  x               o                                                          x  ",
   "  x          xxxx                       xxxxx                              o x  ",
   "  x          x!!x o                                                          x  ",
   "  x       xxxx!!x      &    x                                    xxxxx  &    x  ",
   "  x  @    x!!!!!xxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxx        xxxxxxxx   xxxxxxxxx  ",
   "  xxxxxxxxxxxxxxx           x   x                x   xx   x                     ",
   "                            x!!!x                x!!!!!!!!x                     ",
   "                            x!!!x                x!!!!!!!!x                     ",
   "                            xxxxx                xxxxxxxxxx                     ",
   "                                                                                ",
   "                            x x                                                   "],
  ["                           x   x                                xxxxxxx                                    x!x  ",
   "                          x     x=  =                       xxxx       xxx                                 x!x  ",
   "                         x       x                          xx           xx                                x!x  ",
   "                        x   oo    x            xxx         xx                                              x!x  ",
   "                       x   oooo    x           x!x         x                                    o   o   o  x!x  ",
   "                      x     o       x=  =      x!x         x     o   o                                    xx!x  ",
   "                     x    oooooo     x         x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                    x  &  oooooooo &  x        xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                   xxxxxxxxxxxxxxxxxxxxx                   xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                          xx                xx!!!!!!!!!!!xx              v                      ",
   "                                                             xxxx!!!!!xxxx                                      ",
   "                                             x     x            xxxxxxx        xxx         xxx                  ",
   "                                             x     x                           x x         x x                  ",
   "                                             x     x                             x         x                    ",
   "                                             x     x                             xx        x                    ",
   "                                             xx    x                             x         x                    ",
   "                                             x     x      o  o     x   x         x         x                    ",
   "            xx       xx      xxx  xxx        x     x               x   x      &  x         x                    ",
   "             x       x    o   x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx  o   x   oxx  x o x          x    xx               x   x   x               x                    ",
   "     @       x       x   xx   x   x          x     x               x   x   x      &        x                    ",
   "    xxx      x       x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x   o   x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x      xx!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x   o   x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x       x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x       x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x   x   x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x!!!!!!!x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                o                                                                                             ",
   "               oo                                                                                             ",
   "           &   ooo   &                                                                                        ",
   "        xxxxxxxxxxxxxxxxx                                                                                     ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                     =x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                     =x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                     =x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                 &                     x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x  & xxx &  x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x    &    x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                                                                                                  x x x       ",
   "                                                                o           o                    oxxx x       ",
   "                                                                      &                 &             x       ",
   "       !  o  !                                                x   x xxxxx x   x xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x    x   x        x   x                          x!!!x x   x x!!!x x   x x   x x   x x           ",
   "       x= o  x                                                xxx!x xxx x xxx!x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x!x   x x   x!x   x x   x x   x x     x       ",
   "          o               o                                  xxxxxxxxxx xxxxx!xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "       &  o  &           xxx                              xx                                                  ",
   "      xxxxxxxxx                                                                                               ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                  |xxx|        |xxx|                                                                          ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
